### ISSUE TITLE
Can't find the download button 

### ISSUE THREAD

**Issue by Shpuntzik** [skyguy126/Xposed-SoundCloudDownloader#10]
Hello. I can't seem to find the download button. I searched where you wrote it should be and it's just not there. I will appreciate your help!

**Comment by skyguy126** [comment]
@Shpuntzik It is the triple dot menu usually found at the bottom right on most screens. If you don't see it there might be an error. Can you paste your Android system version, and Xposed log here.

**Comment by rokeno** [comment]
I can confirm. The button is no longer there.

**Comment by skyguy126** [comment]
@rokeno Can you paste your xposed log here, as well as the android system version and soundcloud app version. On my device I still see the download button which is why I am confused.

**Comment by rokeno** [comment]
Ok, i did find the button, but not where I expected it to be. It's only accessible within the song itself.
What I mean, I cannot download a full playlist of songs, or if I open the playlist select each song individually. That is not possible as the "download" text is not there. It's only present if I tap the song and, down on the three white dots, I get the download option.

Is that a normal behaviour?

Thanks.

**Comment by skyguy126** [comment]
@rokeno The download option shouldn't appear on entire playlists, only when pressing the menu on individual tracks, or when using the menu on the now-playing screen, it is a limitation of the current implementation. I can look into adding support for entire playlists if enough interest is shown.

**Comment by rokeno** [comment]
That would be a great addition, but prior to the latest versions, i didn't have to get into the son to download it, i could just enter the playlist and click the small black dots. Now, when i click those, without entering the song, the app crashes. Might be some relation to your app, hence i cannot see the download button in this situation.

**Comment by skyguy126** [comment]
@rokeno Can you post the Xposed log at the time of the crash, system version and app version. As well as steps I would need to repeat the crash. Thanks!

**Comment by rokeno** [comment]
App version: 2018.01.05-release/Flipper version 1.3.6
System version 7.0
Kernel 3.10.107-Martitos-kernel 3.0-edge
Build number SuperStock S8v2 by BugTracker

[xposed_error_20180116_102232[2].log](https://github.com/skyguy126/Xposed-SoundCloudDownloader/files/1634138/xposed_error_20180116_102232.2.log)

**Comment by skyguy126** [comment]
@rokeno I do not see any errors in the Xposed log, could you please send it after the crash occurs. (Clear it, then make the crash happen, and then paste or send here). Other issue, I do not have the latest version of the app yet, google play usually takes a few days to roll out the newest version and until I have that I won't be able to update the hooks.

**Comment by rokeno** [comment]
Myeah, there is nothing in the log, i just cleared it and all i got after the crash ( i did the test earlier, too) is:
[SoundCloud Downloader] Entry
[SoundCloud Downloader] Initialized

...repeated 2 times.

This version os SC is from GooglePlay. 

Update: Strange, the google play link states: 
Current Version
2017.12.18-release - on the website and yet on Android Play store, 2018 is the latest version.

Should i downgrade to a previous version?

Thanks.

Update 2: there is an update on Android Google Play Store: Jan 15.

**Comment by rokeno** [comment]
https://forum.mobilism.org/viewtopic.php?f=1332&t=2392731&hilit=soundcloud - latest.

**Comment by rokeno** [comment]
I can confirm that on version 2017.12.18-release app doesn't crash, the download button is there and i can download them without reaching into the song itself. Apparently they did change the way you fetch the links from each song and contradicts with the code you have in the repository.

**Comment by skyguy126** [comment]
@rokeno Downgrading isn't mandatory as you mentioned it still works on the track page. I won't know to what extent the update broke things until I get the latest version myself, which should be in a few days or less. Strange that the Xposed log isn't reporting any errors. I'll keep you updated.

**Comment by skyguy126** [comment]
@rokeno I just received the update and preliminary testing shows the app is crashing due to SoundCloud ad away possibly. If it is that then I have no control over this issue.

**Comment by skyguy126** [comment]
@rokeno, also getting a debug trace from installer options.

**Comment by skyguy126** [comment]
Fixed with 1ac05b4e8e07964de39dd4af84cda85c340d3402

**Comment by rokeno** [comment]
App still fails after going from 2017 version to the 05 Jan 2018 one, Moving to the latest google app store uupdate, still fails. Same issue, app needs to restart when choosing the dots next to the song. Going inside the song, download option is still there.

**Comment by skyguy126** [comment]
@rokeno Can you post the Xposed log after the crash occurs. Also are you on the 1.4 version for the down-loader?

**Comment by rokeno** [comment]
Steps to reproduce:
1. Uninstalled 2017 version
2. Installed 01.05.2018 release
3. Tried to download, the three black dots turn grey, app stops responding and asks for restart.

Version 1.4 installed, soft reboot done prior to above steps.
![screenshot_20180119-091329](https://user-images.githubusercontent.com/10266176/35138948-863dab4c-fcf9-11e7-948c-b0f777a58969.png)
![screenshot_20180119-091055](https://user-images.githubusercontent.com/10266176/35138949-885b7c74-fcf9-11e7-828e-9e04716728ef.jpg)

No Xposed logs found, Log is empty

**Comment by skyguy126** [comment]
@rokeno I'll try re-implementing the resource locators, hard-coding it seems to malfunction.

**Comment by skyguy126** [comment]
@rokeno It seems to work fine on my phone, can you upload the apk directly from your phone here. Just want to see if the resource ID's I am hard-coding match up.

**Comment by skyguy126** [comment]
@rokeno I found the problem, this module is for 01.**15**.2018 release not 01.**05**.2018 release

**Comment by rokeno** [comment]
Please try this: https://1drv.ms/u/s!AgNP4DN06ZaXhY80qMtwEtZD4y_mQw
I cannot upload 30MB here.

**Comment by rokeno** [comment]
Updated from Android Play Store to 2018-01-15-release, app crashes.
Xposed Logs still empty.

**Comment by skyguy126** [comment]
@rokeno The resource ID's all match up with the apk you sent me (as they should). Make sure it is 1.4, with the 1-15 release. Try reloading the Xposed logs sometimes it doesn't show up. Does the app crash as soon as you press the triple dot menu when on a list view? Confused because I cannot replicate the crash on my device.

**Comment by rokeno** [comment]
Double checked, 2018.01.15-release. Flipper 1.3.6, SoundCloudDownloader to 1.4, xposed activated.
Yes.
Both 1-05 and 1-15 crash.

**Comment by skyguy126** [comment]
@rokeno Try this version, I cannot imagine why it isn't working on your device while it works on mine. Confusing indeed, because I installed the apk you uploaded on my device and the mod works fine.

This is a debug version that dynamically gets the resource id's instead of hard coding them.

**Comment by skyguy126** [comment]
@rokeno Here is the link: https://drive.google.com/open?id=1hA3yLuiEtTQkNvTiWZBfnjm26gQi0-Be

**Comment by rokeno** [comment]
hey, i can tell you that this is now working.
The only thing that is odd now (might be that is in debug mode), keeps asking me where i wanna download, although the setting in the app clearly states: /sdcard/music/

**Comment by skyguy126** [comment]
@rokeno I'll fix that in another incremental version, has to do with not resetting properties. Does it work without crashing the entire app now, **v1.4 debug**?

**Comment by rokeno** [comment]
Yes, it does, i no longer have issue.

**Comment by skyguy126** [comment]
Fixed with 56b4e97ecede42c57d92a495742eaf517bf5b7dd

**Comment by rokeno** [comment]
Thanks alot!

**Comment by gugucarv** [comment]
My SoundCloud release is 2018.10.9

Downloads do not appear for me

**Comment by skyguy126** [comment]
Known issue - unfortunately I don't have much free time in foresight. I'd recommend rolling back your soundcloud version and disabling automatic updates :/

**Comment by gugucarv** [comment]
Hi. Installed 2018.09.25 release and now it's working. Ty

**Comment by peterkor** [comment]
it would be great to have a possibility to download whole playlist by one button :)
